### PR TITLE
#39, #47 - Setup app architecture

### LINKED ISSUE #39: Setup themes and colors in android project
**Describe the feature**
Setup, colors, themes and font for the project to use Material 3
- [x] Set theme to use Material 3
- [x] Set the colors from Figma into colors.xml 
- [x] Get Roboto font as a [downloadable font](https://developer.android.com/develop/ui/views/text-and-emoji/downloadable-fonts#via-android-studio) for the project 

**Additional context**
Setting up and using Material components can be seen[ here
](https://github.com/material-components/material-components-android/tree/master/docs)

### LINKED ISSUE #47: Setup Navigation Bar
**Describe the feature**
image
Related to #46. Implement navigation bar that navigates to empty activities

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by MaxxonTan**
Closes #47 , Closes #39. **Sorry it's a long read but go through additional context below and don't merge until everyone approved this PR**

# Summary

- Change theme to use Material 3 in `themes.xml`
- Added colors from Figma to `colors.xml`
- Setup folder structure to loosely follow Android's [recommended app architecture ](https://developer.android.com/topic/architecture)
- Added Navbar that navigates to their respective fragments
- Added sample in profile to demo `ViewModel` and `LiveData`

# Screenshot 

navbarsetup

# Additional Context

The app architecture I setup is based **loosely** on the official [recommended app architecture](https://developer.android.com/topic/architecture). In the folder structure, `ui` will hold all the code responsible for the ui and `data` will hold all the classes related to data such as the model classes and repository classes (explained more below). This is so that we can have better [separation of concerns](https://help.sap.com/doc/abapdocu_753_index_htm/7.53/en-US/abenseperation_concerns_guidl.htm#:~:text=Separation%20of%20concerns%20is%20a,and%20arrangement%20in%20software%20layers.) and cleaner code.

To summarize some of the concepts quickly if you don't want to read the docs:
- [**ViewModel**](https://developer.android.com/topic/libraries/architecture/viewmodel). Instead of saving states in fragment / activity itself, you save it into a ViewModel class which you instantiate the onCreate of a fragment / activity. ViewModel also contains [ui logic](https://developer.android.com/topic/architecture/ui-layer/stateholders#logic).
- [**LiveData**](https://developer.android.com/topic/libraries/architecture/livedata). A wrapper for our data in ViewModel that makes it so that we can just suscribe to the changes and make it update the ui automically instead of having to get the data manually after making changes.
- **Repositories**. Repository classes are the only classes that connects to Firebase and exposes the data to ViewModel. Our ui in fragments / activities and ViewModels should never call Firebase directly. Repository classes contains [business logic](https://developer.android.com/topic/architecture/ui-layer/stateholders#logic) such as adding a QR Code to database.
- [**View binding**](https://developer.android.com/topic/libraries/view-binding). It basically replaces findViewById with [better features](https://developer.android.com/topic/libraries/view-binding#findviewbyid). Example:

```
// Using findViewById
class exampleFragment{
	EditText stationNameInput;
	EditText dateInput;
	RadioGroup fuelTypeRadioGroup;
	EditText fuelAmountInput;
	EditText pricePerLitreInput;
	Button saveButton;
	Button deleteButton;

	public View onCreateView(...){
		View dialogView = inflater.inflate(R.layout.visit_dialog, null);
	
		stationNameInput = dialogView.findViewById(R.id.stationNameInput);
                dateInput = dialogView.findViewById(R.id.dateInput);
                fuelTypeRadioGroup = dialogView.findViewById(R.id.fuelTypeRadioGroup);
                fuelAmountInput = dialogView.findViewById(R.id.fuelAmountInput);
                pricePerLitreInput = dialogView.findViewById(R.id.pricePerLitreInput);
    }
}
```
will turn into:
```
// Using findViewById
// Using view binding
class exampleFragment{
	// The VisitDialogBinding class is autogenerated
	VisitDialogBinding binding;

	public View onCreateView(...){
		View dialogView = inflater.inflate(R.layout.visit_dialog, null);

		binding = VisitDialogBinding.inflate(getLayoutInflater());

		// To access any view in this fragment class, we can just call
		binding.stationNameInput or binding.deleteButton
	}
}
```

### CODE REVIEW

**Comment by harryz6560** [comment]
looks good to me!

**Review by lkaijie — COMMENTED** [review]
looks good

**Review by vtrieu5 — COMMENTED** [review]
Seems good

**Review by vtrieu5 — COMMENTED** [review]
Sorry for the multiple reviews I wasn't sure if I was supposed to explicitly approve or just comment

**Comment by MaxxonTan** [comment]
> Sorry for the multiple reviews I wasn't sure if I was supposed to explicitly approve or just comment

nope you're good

**Review by Siddharth-Chhatbar — APPROVED** [review]
looks good

**Review by harryz6560 — APPROVED** [review]

**Review by mrbubbleman — COMMENTED** [review]
looks good!

**Pull request merged**
