### PR TITLE
Adding models and refactor

### PR DESCRIPTION
**Pull request by MaxxonTan**
# Description

- Added **model** directory containing model classes `Comment`, `Location`, `Player` and `QRCode`
- Added **utils** directory containing all the utility classes
- Refactor #52 a little bit
- Added `local.properties` to gitignore
- A lot of line changes because the formatter removed a lot of unused imports

# Additional Context

I've added some empty methods in `QRCodeUtil.java`, `QRCodeRepository.java` and `PlayerRepository.java`. Everyone please fill it out as needed.

### CODE REVIEW

**Review by vtrieu5 — APPROVED** [review]
Looks good

**Comment by Siddharth-Chhatbar** [comment]
Looks good

**Review by Siddharth-Chhatbar — CHANGES_REQUESTED** [review]
A deviceID object should be added to the Player class to link the device to the player

**Review by Siddharth-Chhatbar — APPROVED** [review]
looks good

**Comment by mrbubbleman** [comment]
looks good

**Pull request merged**
